version: "3.9"

services:
  app:
    image: php:${PHP_VERSION}-fpm-alpine${ALPINE_VERSION}
    container_name: ${PROJECT_NAME}
    restart: unless-stopped
    environment:
      PHP_IDE_CONFIG: 'serverName=localhost'
      SITENAME: ${PROJECT_NAME}
      DB_NAME: ${PROJECT_NAME}
    user:
      ${UID}:${GID}
    volumes:
      - ./www:/var/www/html:z
      - ./.docker/assets/php-conf/default.ini:/usr/local/etc/php/conf.d/default.ini
      - ./.docker/assets/php-conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./.docker/assets/php-conf/php-smtp.ini:/usr/local/etc/php/conf.d/php-smtp.ini
    ports:
      - 9000:9000

  nginx:
    container_name: nginx
    image: nginx:${NGINX_VERSION}-alpine
    restart: unless-stopped
    volumes:
      - ./www:/var/www/html:delegated
      - ./logs:/var/log/nginx
      - ./.docker/assets/nginx-conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.docker/assets/certs/ssl-cert-snakeoil.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem
      - ./.docker/assets/certs/ssl-cert-snakeoil.key:/etc/ssl/private/ssl-cert-snakeoil.key
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443 # 3000:443 to fix URL without port when using BrowserSync

  mysql:
    container_name: mysql
    image: mysql:${MYSQL_VERSION}
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: webdev
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: ${PROJECT_NAME}
    user:
      ${UID}:${GID}
    volumes:
      - mysqldata:/var/lib/mysql
      - ./database:/database
      - ./.docker/assets/mysql-conf/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf

  webpack:
    container_name: webpack
    image: node:${NODE_VERSION}-slim
    restart: unless-stopped
    depends_on:
      - yarn
      - app
    command: bash -c "chmod u+x /usr/local/bin/wait-node-install.sh && wait-node-install.sh && yarn start"
    links:
      - nginx
    volumes:
      - ./www:/home/node/${PROJECT_NAME}:rw
      - ./.docker/bin/wait-node-install.sh:/usr/local/bin/wait-node-install.sh
    working_dir: /home/node/${PROJECT_NAME}
    ports:
      - 3000:3000 # Port pour BrowserSync # remove this line to fix URL without port when using BrowserSync
      - 3001:3001 # Port pour BrowserSync
      - 8089:8089 # Port pour webpack

  yarn:
    container_name: yarn
    image: node:${NODE_VERSION}-slim
    restart: 'no'
    command: bash -c "yarn install --verbose --pure-lock && touch ./node_modules/.install-done"
    entrypoint: ""
    user:
      ${UID}:${GID}
    volumes:
      - ./www:/home/node/${PROJECT_NAME}:delegated
    working_dir: /home/node/${PROJECT_NAME}

  composer:
    container_name: composer
    image: composer:${COMPOSER_VERSION}
    restart: 'no'
    command: bash -c "composer install -vvv --ignore-platform-reqs --no-interaction --no-progress && echo 'Project ready on https://localhost'"
    depends_on:
      - app
    entrypoint: ""
    user:
      ${UID}:${GID}
    volumes:
      - ./www:/app:cached

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - 1025:1025 # SMTP server
      - 8025:8025 # Web UI

  pma:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: webdev
      PMA_PASSWORD: root
    ports:
      - 8080:80

volumes:
  mysqldata:
